### ISSUE TITLE
Trying to setup personal relay through cloudflare: "initial bytes are not magic"

### ISSUE THREAD

**Issue by jathek** [schollz/croc#522]
## Describe the bug
I set up a personal relay using the docker container, using the below compose file. When someone tries to receive the file, they get the following error: `initial bytes are not magic: 48545450`. Not sure what's going on. Is croc not waiting long enough to get redirected through cloudflare's proxying? Is cloudflare just not proxying the traffic properly? If I'm reading [the documentation correctly, those ports should work](https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/).

Ports are properly forwarded and the relay works if cloudflare proxying is disabled for the subdomain I'm using.

## To Reproduce
1. Create relay on computer with ports compatible with cloudflare proxy (docker-compose)
2. Initiate send using that relay, using the cloudflare subdomain `croc --pass CROC_PASS --relay "croc.CLOUDFLAREDOMAIN.com:2052" send --hash imohash SOMEFILE`
3. Initiate receive using that relay, using the cloudflare subdomain `croc --relay croc.CLOUDFLAREDOMAIN.com:2052 --pass CROC_PASS CODE_PHRASE`
4. magic bytes error

## Expected behaviour
Croc receive should hopefully work through Cloudflare proxy.

## Version
croc version v9.6.2-3b81934

## Additional context

<details><summary>docker-compose</summary>

```yml
  # croc - Easily and securely send things from one computer to another 🐊 📦
  croc:
    image: schollz/croc
    container_name: croc
    restart: unless-stopped
    entrypoint: ["sh", "-c", "/croc --pass \\$CROC_PASS relay --ports 2052,2082,2086,2095"]
    env_file: 
      - "$SECRETSDIR/croc.env"
    hostname: croc
    networks:
      lan_macvlan:
        ipv4_address: $CROC_IP
    mac_address: $CROC_MAC
    ports:
      - 2052:2052/tcp # communication
      - 2082:2082/tcp # data transfer
      - 2086:2086/tcp # data transfer
      - 2095:2095/tcp # data transfer
      # - 9009-9013:9009-9013 # default
    volumes:
      - $CONTDIR/croc:/.config/croc
```
</details>
