### ISSUE TITLE
Traefik 3.0

### ISSUE THREAD

**Issue by OisinHick** [schollz/croc#908]
Hey All,

First off to the maintainer: thanks for your hard work - love this tool.

Is this project's docker relay compatible with traefik 3 reverse proxy?

If so, I would love any direction/ideas as to how this can be implemented. Hopefully it can help me or anyone else at a later date!

**Comment by thelittlefox** [comment]
Traefik can proxy TCP/IP traffic, so I believe the answer is yes.

**Comment by vaygr** [comment]
This did not work for me. Are you sure traffic is going through the relay and not locally? I have the sending local machine completely firewalled and the receiving one failed to establish the connection.

To test: send with `--no-local` flag.

@schollz is it possible to use a single port on the relay -- the one that's also a base port? When I start the relay with `relay --port 9009 --ports 9009`, and try to receive, croc crashes with the following:

```shell
[debug] 06:43:55 comm.go:83: comm.NewConnection failed: dial tcp: lookup tcp/ok: unknown port
[debug] 06:43:55 tcp.go:493: comm.NewConnection failed: dial tcp: lookup tcp/ok: unknown port
panic: comm.NewConnection failed: dial tcp: lookup tcp/ok: unknown port

goroutine 37 [running]:
github.com/schollz/croc/v10/src/croc.(*Client).processMessagePake.func1(0x0)
        github.com/schollz/croc/v10/src/croc/croc.go:1461 +0x4ad
created by github.com/schollz/croc/v10/src/croc.(*Client).processMessagePake in goroutine 19
        github.com/schollz/croc/v10/src/croc/croc.go:1441 +0x745
```

The only way I could make it work was adding _an additional port_ with port-forwarding directly on the container:

```yml
    ports:
      - 9012:9012
```

which will make traffic run not through traefik proxy,

and then running the relay with: `relay --port 9009 --ports 9009,9012`.

**Comment by vaygr** [comment]
@OisinHick the comment here and in the PR are different and target different issues. The comment in the PR is about TLS, which I don't think will ever work regardless of the certificate vendor.

The comment here is talking about the error that I see when I use just one (base) port. I mentioned the `--no-local` flag above. Were you able to verify this, confirm it works and traffic traffic goes through traefik?

**Comment by tekdoc** [comment]
Thanks to @OisinHick I now have a self-hosted croc relay working behind Traefik. I just wanted to point out a couple things though:

First, as @vaygr mentioned, TLS is not used or needed in this situation (see explanation [here](https://community.traefik.io/t/tcp-tls-server-with-non-tls-tcp-router/1539)). Also, once you have this configured, there is no need to specify the port when you run croc, and that along with using the FQDN instead of just an IP address was my motivation for setting this up in the first place. Finally, I think instructions on how to do this are really beyond the scope of the croc documentation - especially since despite being rock solid once it's working, Traefik is rather difficult for most people to understand and configure.

That being said, here are the relevant sections from my config (with only 2 ports opened since I am the only user on my network):

### dynamic.yml

```
tcp:
  routers:
    croc1:
      entrypoints:
        - croc1
      rule: "HostSNI(`*`)"
      service: croc1
    croc2:
      entrypoints:
        - croc2
      middlewares:
        - onlyme
      rule: "HostSNI(`*`)"
      service: croc2

  services:
    croc1:
      loadBalancer:
        servers:
          - address: 192.168.200.100:9009
    croc2:
      loadBalancer:
        servers:
          - address: 192.168.200.100:9013
```
### traefik.yml
```
entryPoints:
...
  croc1:
    address: ':9009'
  croc2:
    address: ':9013'
```
